### ISSUE TITLE
libxnet-lib.so not found

### ISSUE THREAD

**Issue by forgetW** [yangqingyuan/TekiXquic#2]
Process: com.example.xquicdemo, PID: 23788
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.xquicdemo-VJaRCt8FRfcluiUOh4WlJA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.xquicdemo-VJaRCt8FRfcluiUOh4WlJA==/lib/arm, /data/app/com.example.xquicdemo-VJaRCt8FRfcluiUOh4WlJA==/base.apk!/lib/armeabi-v7a, /system/lib]]] couldn't find "libxnet-lib.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1668)
        at com.lizhi.component.net.xquic.native.XquicLoader.loadLib(XquicLoader.kt:18)
        at com.lizhi.component.net.xquic.native.XquicShortNative.<init>(XquicShortNative.kt:10)
        at com.lizhi.component.net.xquic.impl.XAsyncCall.<init>(XAsyncCall.kt:73)
        at com.lizhi.component.net.xquic.impl.XRealCall.enqueue(XRealCall.kt:63)
        at com.example.xquicdemo.ShortConnActivity.request(ShortConnActivity.kt:156)
        at com.example.xquicdemo.ShortConnActivity.get(ShortConnActivity.kt:119)
        at com.example.xquicdemo.ShortConnActivity.access$get(ShortConnActivity.kt:24)
        at com.example.xquicdemo.ShortConnActivity$onCreate$1$1.invokeSuspend(ShortConnActivity.kt:57)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by yangqingyuan** [comment]
设备型号可以描述一下吗
